spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true

  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 3
    pool:
      maxActive: 1000
      maxIdle: 600
      minIdle: 1
      maxWait: -1
      testOnBorrow: true
      numTestsPerEvictionRun: 1024
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 1800000
      softMinEvictableIdleTimeMillis: 1800000
      testWhileIdle: true
      blockWhenExhausted: false
  # ==============================================================
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    # 开启ACK
    listener:
      simple:
        acknowledge-mode: manual
  kafka:
    bootstrap-servers: yuuki-kakfa:9092
    listener:
      missing-topics-fatal: false
    producer:
      # 每次批量发送消息的数量
      batch-size: 16
      # 缓存容量
      buffer-memory: 33554432
      #设置大于0的值，则客户端会将发送失败的记录重新发送
      retries: 0
      # 指定消息key和消息体的编解码方式 UTF-8
      key-serializer: org.apache.kafka.account.serialization.StringSerializer
      value-serializer: org.apache.kafka.account.serialization.StringSerializer
  elasticsearch:
    host: 106.53.237.234:9200,106.53.237.234:9200
    username:
    password:
    connectNum: 10
    connectPerRoute: 50
    token: es-token
    charset: UTF-8
    scheme: http
    client:
      connectTimeOut: 5000
      socketTimeout: 15000



